### ISSUE TITLE
Components Do not show up in Drag to Page Menu

### ISSUE THREAD

**Issue by Tigerlady** [MasaCMS/MasaCMS#129]
When doing a front end edit the Components Option doesn't show up in the Drag to Page menu. Below is an image of old Mura on Right and MASA on the left. 

![image](https://user-images.githubusercontent.com/1850313/191580888-c772fb3c-e411-4602-89b5-fbc4720eb129.png)

**Comment by grantshepert** [comment]
Make sure  contenttypes="*" is in the config.xml.cfm <mura> tag ... i.e. 

<mura name="MyComponent" contenttypes="*" iconclass="mi-rebel"/>

**Comment by Tigerlady** [comment]
Thank you. Just for everyone else, the actual file is core/modules/v1/component/config.xml.cfm the * was missing.  I added it and then refreshed the application. The components came back in the navigation. 

`<mura name="Component"
    contenttypes="*"
    iconclass="mi-clone"
    legacyobjectfile="../dsp_template.cfm"
/>`

**Comment by guustnieuwenhuis** [comment]
Grant is right about the fix, if you want the "component" module to be active. But, you'll change the core of Masa CM, that's not upgrade save!

We won't make the "component" module active, because the correct approach to add a component to a page is to use the "text" module and select a component in there.

**Comment by Tigerlady** [comment]
I didn't know I could add components that way.  I checked it out, and works.  Thank you for the information.  I know several things did change with MASA.
