### ISSUE TITLE
Need a page name above a level

### ISSUE THREAD

**Issue by Tigerlady** [MasaCMS/MasaCMS#182]
Ok, so I am building a chamber site that peer navigation system. But I would like to pull the upper level nav name.  For example:

Restaurants/Lounges & Bars are the top-level nav; there are pages under this.  But for the purposes of a header, I want to dynamically have the top-level directory show at the top of the page.  Not sure if this can be done but it would be a great help. 

![image](https://user-images.githubusercontent.com/1850313/230985878-0483af8e-815d-4d78-b79c-9fe63ea35a20.png)

**Comment by brimard** [comment]
<cfoutput> <div class="well"> <cfif listlen($.content('path'),",") EQ
"2"> <cfset navParentID =
$.content('contentID')> 
#$.dspNestedNav(navParentID)#        <cfelseif
listlen($.content('path'),",") EQ "3">
<h4><a
href="/#$.event('siteID')#/index.cfm/#$.getFileName()#">#$.gettitle()#</a></h4>
<cfset navKidsCount = $.content().getKidsQuery().recordcount> <cfset
navParentID = $.content('parentID')> <cfif navKidsCount EQ "0">
#$.dspNestedNav(navParentID,'1','1','default')# <cfelse> #$.dspSubNav()#
</cfif> <cfelseif listlen($.content('path'),",") EQ "4"> <h4><a
href="/#$.event('siteID')#/index.cfm/#$.getFileName()#">#$.gettitle()#</a></h4>
<cfset navKidsCount = $.content().getKidsQuery().recordcount> <cfset
navParentID = $.content('parentID')> <cfif navKidsCount EQ "0">
#$.dspNestedNav(navParentID,'1','1','default')# <cfelse> #$.dspSubNav()#
</cfif> <cfelse> <cfset eventParentID =
listgetat($.content('path'),"4",",")> <cfset eventParentContent =
$.getBean('content').loadBy(contentID=eventParentID)> <h4><a
href="/#$.event('siteID')#/index.cfm/#eventParentContent.getFileName()#">#eventParentContent.gettitle()#</a></h4>
#$.dspPeerNav()#

The above is old, but this is how we handled the exact need many years
ago.Been a while since I played with the various path depths, so something
you'd need to play around with your specific use case. And again, this is
older, so likely more elegant/better ways to do it nowadays.
