### ISSUE TITLE
Script code pasted in component gets deleted

### ISSUE THREAD

**Issue by russianlife** [MasaCMS/MasaCMS#252]
**Describe the bug**
We are trying to paste some script code into a component (to create a buy button for Stripe), and every time on save it deletes some of the code. Why would it alter the code?

**To Reproduce**
1. Go to component, edit or add some script text, and see if it hangs on.

Here is the snippet can't paste, with dummy code in our account number info.
<script async
  src="https://js.stripe.com/v3/buy-button.js">
</script>

<stripe-buy-button
  buy-button-id="buy_btn_XXX"
  publishable-key="pk_live_XXX"
>
</stripe-buy-button>

After save, it deletes all the stuff from <stripe-buy-button on

**Additional context**

**Comment by guustnieuwenhuis** [comment]
Masa doesn't allow this in text modules/components/etc. because of security reasons.

What you could do, is use the "embed" module to add this code. BUT... Our suggestion is to create a custom module that includes this code. Then you can drag that module on the page to add this functionality. A custom module would be much safer then the embed module.
