### ISSUE TITLE
Only past events show up in the calendar.

### ISSUE THREAD

**Issue by Tigerlady** [MasaCMS/MasaCMS#277]
**Describe the bug**
Add an event item to a calendar.  Select a date in the future.  Masa no longer throws an error when entering an event with a Long month title date, but it does not show the event in the calendar.  

However, interestingly enough, the calendar shows events with an expiration date set to them from the past.  These should not show on the calendar. 

I am running on the latest version of MASA 7.4.5, which Just updated today. 

**To Reproduce**
Add an event to the calendar schedule for a date in the future.
Have a page on the site that has a calendar view.
The event in the future does not show on the calendar.
Create an event that is in the past. It will show on the calendar. 

**Expected behavior**
Events in the future should show on the calendar, and if they have an expiration date, they should no longer show on the calendar.

**Comment by jeroenweareorangeeu** [comment]
Hi,

(tested om Masa 7.4.6.)

Soo looked into this and I can create future events in the Calendar just fine:

![image](https://github.com/MasaCMS/MasaCMS/assets/83004496/99e4ece3-86f6-44ab-95ce-0b0af218f13a)

You can set the date in the 'Scheduling' part of child item under the Calendar:

![image](https://github.com/MasaCMS/MasaCMS/assets/83004496/e2278804-e824-41f8-9233-d61c2d31593c)

----
Now as for the expiration of events in the Calendar; this simply isnt supported.

So normal content it can be Scheduled in a *range*:

![image](https://github.com/MasaCMS/MasaCMS/assets/83004496/3626fd28-2f07-4ef8-a538-6793a2a6041b)

Which makes it possible to only showing them for a certain period of time.

Events (child items of the Calendar) only have a * single date*  option under 'Scheduling'. 
Compare the second screenshot with third screenshot to see the difference.

There may be some confusion about 'expiration', since under 'Publishing' there is also an 'Expiration' part.

![image](https://github.com/MasaCMS/MasaCMS/assets/83004496/1baf1b1a-3e10-4c88-b38f-8206b8e29829)

For what I can tell at the moment, this is only used for administrative purposes and possibly to notify content managers that content had expired and needs to be updated. There is no functionality behind this. 

Hope this helps to clarify things.
