### ISSUE TITLE
Browse Assets for Link Content Type Not Working

### ISSUE THREAD

**Issue by mikechy** [MasaCMS/MasaCMS#296]
**Describe the bug**
Browse Assets Button Broken

**To Reproduce**
Add a LINK type to a folder, the Browse Assets button does nothing.  Console shows there are some CKEDITOR Conflicts

**Expected behavior**
You should be presented with assets to link to

**Screenshots**
![image](https://github.com/MasaCMS/MasaCMS/assets/7227628/e84f5bcf-fa0e-4d57-a097-595e9556cfc3)

**Desktop (please complete the following information):**
 - OS: Windows 10
 -  - Browser Latest Chrome
Version 122.0.6261.129 (Official Build) (64-bit)

**Environment (please complete the following information):**
 - OS: Windows 2022 Server
 - Lucee 5.3.8.189
 - Masa 7.4.6
 - Database MSSQL 2019

**Comment by jeroenweareorangeeu** [comment]
Hi,

Looked into this. So there are no console errors, just warnings. 
It seems that the button 'Browse Assets' has been placed there, but doesn't do anything.
Its not supposed to do anything, because only you can supply an URL (a *link* to another site) for this Content Type.
Created a PR to remove this button from this panel. 
Thank you for submitting this bug.

**Comment by jeroenweareorangeeu** [comment]
Will be fixed in Masa 7.4.7. release.
